---
application:
  name: "ubproxy"
  project: "ub"
  organization: "QoveryCommunity"
  storage:
  - name: "data"
    size: "20"
    type: "ssd"
    mount_point: "/mnt/data"
databases:
- type: "MYSQL"
  name: "wechat-mysql"
  version: "8.0"
- type: "REDIS"
  name: "wechat-redis"
  version: "8.0"
routers:
- name: "main-ubproxy"
  routes:
  - application_name: "ubproxy"
    paths:
    - "/*"
