---
application:
  name: "ubproxy"
  project: "ub"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "wechat-mysql"
  version: "8.0"
- type: "REDIS"
  name: "wechat-redis"
  version: "8.0"
routers:
- name: "main-ubproxy"
  routes:
  - application_name: "ubproxy"
    paths:
    - "/*"
